import React from 'react'
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom'
import { AuthProvider, useAuth } from './context/AuthContext'
import Layout from './components/Layout'
import Login from './pages/Login'
import Dashboard from './pages/Dashboard'

// Autogenerated Module Imports
import ClientPage from './pages/ClientPage'
import MasterPage from './pages/MasterPage'
import RequisitionPage from './pages/RequisitionPage'
import AllocationPage from './pages/AllocationPage'
import CandidatePage from './pages/CandidatePage'
import ScreeningPage from './pages/ScreeningPage'
import ShortlistingPage from './pages/ShortlistingPage'
import InterviewPage from './pages/InterviewPage'
import OfferPage from './pages/OfferPage'
import JoiningPage from './pages/JoiningPage'
import TaskPage from './pages/TaskPage'
import ReportPage from './pages/ReportPage'
import AuditPage from './pages/AuditPage'
import SettingPage from './pages/SettingPage'

const PrivateRoute = ({ children }) => {
  const { currentUser } = useAuth();
  return currentUser ? <Layout>{children}</Layout> : <Navigate to="/login" />;
}

function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          <Route path="/login" element={<Login />} />
          <Route path="/dashboard" element={<PrivateRoute><Dashboard /></PrivateRoute>} />
          
          {/* Autogenerated Module Routes */}
          <Route path="/clients" element={<PrivateRoute><ClientPage /></PrivateRoute>} />
          <Route path="/master" element={<PrivateRoute><MasterPage /></PrivateRoute>} />
          <Route path="/requisitions" element={<PrivateRoute><RequisitionPage /></PrivateRoute>} />
          <Route path="/allocations" element={<PrivateRoute><AllocationPage /></PrivateRoute>} />
          <Route path="/candidates" element={<PrivateRoute><CandidatePage /></PrivateRoute>} />
          <Route path="/screening" element={<PrivateRoute><ScreeningPage /></PrivateRoute>} />
          <Route path="/shortlisting" element={<PrivateRoute><ShortlistingPage /></PrivateRoute>} />
          <Route path="/interviews" element={<PrivateRoute><InterviewPage /></PrivateRoute>} />
          <Route path="/offers" element={<PrivateRoute><OfferPage /></PrivateRoute>} />
          <Route path="/joining" element={<PrivateRoute><JoiningPage /></PrivateRoute>} />
          <Route path="/tasks" element={<PrivateRoute><TaskPage /></PrivateRoute>} />
          <Route path="/reports" element={<PrivateRoute><ReportPage /></PrivateRoute>} />
          <Route path="/audit" element={<PrivateRoute><AuditPage /></PrivateRoute>} />
          <Route path="/settings" element={<PrivateRoute><SettingPage /></PrivateRoute>} />

          {/* Placeholders for modules on the sidebar that don't have scaffolded pages yet */}
          <Route path="/users" element={<PrivateRoute><div className="p-8">User Management Pending</div></PrivateRoute>} />
          <Route path="/roles" element={<PrivateRoute><div className="p-8">Role & Permission Pending</div></PrivateRoute>} />
          <Route path="/approvals" element={<PrivateRoute><div className="p-8">Approval Workflow Pending</div></PrivateRoute>} />
          <Route path="/pipeline" element={<PrivateRoute><div className="p-8">Candidate Pipeline Pending</div></PrivateRoute>} />
          <Route path="/crm" element={<PrivateRoute><div className="p-8">CRM Pending</div></PrivateRoute>} />
          <Route path="/notifications" element={<PrivateRoute><div className="p-8">Notifications Pending</div></PrivateRoute>} />
          <Route path="/documents" element={<PrivateRoute><div className="p-8">Document Management Pending</div></PrivateRoute>} />
          <Route path="/faqs" element={<PrivateRoute><div className="p-8">FAQs Pending</div></PrivateRoute>} />
          <Route path="/config" element={<PrivateRoute><div className="p-8">System Configuration Pending</div></PrivateRoute>} />

          <Route path="/" element={<Navigate to="/dashboard" />} />
        </Routes>
      </Router>
    </AuthProvider>
  )
}

export default App
